name: Aaron Rutherford
favicon: null
layout_spectrum: 0.5445734050590545
typography_spectrum: 0.20770218828693032
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.22330674692057073
  lightness: 0.36617639870382845
  saturation: 0.9982566421385854
  rhythmicContrast: 0.03734312974847853
purpose: []
